### ISSUE TITLE
Can't catch an href

### ISSUE THREAD

**Issue by CorentinDy** [davidfoliveira/node-jscrap#1]
Hi , 
I would like to try your sample because i'm working too on the kernel.org website but i can't catch the href link to download the last kernel edition (for exemple).

I'm trying something like that : 

```
var lkerneldl = ($("#latest_button > a.attr('href')").text().trim());
```

Is something wrong ?

**Comment by davidfoliveira** [comment]
Hi,

The .attr('href') should be outside of the CSS selector.
Example:

```
var
    jscrap = require('jscrap');

jscrap.scrap('http://www.kernel.org',function(err,$){
    console.log($("#latest_button > a").attr('href').trim());
});
```

**Comment by CorentinDy** [comment]
Thanks a lot ! 
You make my day ;)
